server.port: 10001

spring:
  profiles:
    active: local

---
spring:
  profiles: local
  data:
    dynamodb:
      entity2ddl:
        auto: create-only
        gsiProjectionType: ALL
        readCapacity: 100
        writeCapacity: 100